# 统计代码请直接替换 _partial/footer.ejs 文件里的代码

theme_name: TTStyle
site_url: http://thisisadu.github.io

# 社交信息
github: "http://github.com/thisisadu"
qq: "mailto:877904574@qq.com"


# 托管服务器
gitPagesServerAddr: "http://github.com"
gitPagesServerName: "Github"


# 是否在新窗口打开链接
open_in_new: true

# favicon
favicon: /images/favicon.png

#你的头像url
avatar: /images/favicon.png

#是否高亮代码。默认开启
highlightCode: true

#代码高亮样式名称
## 内置样式名称5种：idea xcode solarized-dark solarized-light googlecode
highlightStyle: xcode

#捐赠相关。默认微信打赏
donateEnable: true
